/*
  ============================================================
  GOLAGHAT DISTRICT EMERGENCY OPERATIONS — GEOSPATIAL & TELEMETRY DATASET
  Sources: District Administration Golaghat (DDMA),
  Assam State Disaster Management Authority (ASDMA),
  Central Water Commission (CWC), Assam Water Resources Dept,
  Assam PWD, Directorate of Agriculture & Animal Husbandry,
  District Health Society Golaghat, National Health Mission Assam,
  NRSC / ISRO Flood Inundation Products.
  ============================================================
*/

export const GOLAGHAT_CENTER = [26.5200, 93.9700];
export const GOLAGHAT_DEFAULT_ZOOM = 10;

// Base Map Tile Layers Config
export const BASE_LAYERS = {
  dark: {
    name: "Dark Operational",
    url: "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",
    attribution: '&copy; <a href="https://carto.com/">CARTO</a> &copy; OpenStreetMap | DDMA Golaghat',
    maxZoom: 19,
    subdomains: "abcd",
  },
  street: {
    name: "Standard Street",
    url: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> | DDMA Golaghat',
    maxZoom: 19,
  },
  satellite: {
    name: "Satellite Imagery",
    url: "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community',
    maxZoom: 18,
  },
  terrain: {
    name: "Terrain Topo",
    url: "https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",
    attribution: 'Map data: &copy; OpenStreetMap, SRTM | Map style: &copy; OpenTopoMap',
    maxZoom: 17,
  },
  hybrid: {
    name: "Hybrid Voyager",
    url: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png",
    attribution: '&copy; CARTO &copy; OpenStreetMap | DDMA Golaghat',
    maxZoom: 19,
    subdomains: "abcd",
  },
};

// Golaghat District Outer Boundary Polygon
export const GOLAGHAT_DISTRICT_BOUNDARY = [
  [26.7800, 93.5200],
  [26.7400, 93.7500],
  [26.7100, 94.0800],
  [26.4800, 94.1200],
  [26.1500, 93.9500],
  [25.9800, 93.8200],
  [26.2200, 93.6800],
  [26.4500, 93.7200],
  [26.6200, 93.4500],
  [26.7800, 93.5200],
];

// Major Rivers & Tributaries Traversing Golaghat District
export const GOLAGHAT_RIVERS = [
  {
    name: "Dhansiri (South) River — Main Channel",
    color: "#ef4444",
    weight: 4,
    status: "Flowing 0.52m Above Danger Level at Numaligarh",
    coordinates: [
      [26.0500, 93.8200],
      [26.2500, 93.8500],
      [26.4200, 93.9200],
      [26.5186, 93.9678],
      [26.5800, 93.8500],
      [26.6200, 93.7500],
      [26.6800, 93.6500],
    ],
  },
  {
    name: "Doyang River (Major Tributary)",
    color: "#f97316",
    weight: 3.5,
    status: "0.20m Above Danger Level near Khumtai",
    coordinates: [
      [26.2800, 94.0200],
      [26.4500, 93.9800],
      [26.5800, 93.9100],
      [26.6350, 93.8600],
    ],
  },
  {
    name: "Gelabil River (Bokakhat Flood Channel)",
    color: "#0284c7",
    weight: 3,
    status: "Flowing Near High Warning Level",
    coordinates: [
      [26.5600, 93.5400],
      [26.5900, 93.6100],
      [26.6500, 93.6600],
    ],
  },
  {
    name: "Brahmaputra River (Northern District Fringe)",
    color: "#0369a1",
    weight: 4.5,
    status: "High Discharge Inundating Kaziranga Lowlands",
    coordinates: [
      [26.7500, 93.4200],
      [26.7200, 93.6000],
      [26.7000, 93.8000],
      [26.6800, 94.0500],
    ],
  },
  {
    name: "Kakodonga River (Jorhat-Golaghat Border)",
    color: "#0ea5e9",
    weight: 2.5,
    status: "Embankment Seepage Controlled in Dergaon",
    coordinates: [
      [26.5200, 94.0800],
      [26.6200, 94.0200],
      [26.7100, 93.9800],
    ],
  },
];

// Golaghat Revenue Circles (Administrative Hierarchy with Impact Metrics)
export const GOLAGHAT_CIRCLES_GEO = [
  {
    id: "CIR-01",
    circle: "Bokakhat Revenue Circle",
    subdivision: "Bokakhat Civil Sub-division",
    center: [26.5850, 93.6050],
    severity: "Critical",
    populationAffected: 64800,
    familiesAffected: 13800,
    villagesAffected: 68,
    deaths: 3,
    housesDamaged: 1920,
    cropAreaHa: 3400,
    reliefCamps: 16,
    campInmates: 5600,
    status: "Kaziranga fringes & Gelabil submerged; NH-715 restricted at Km 92",
    source: "SDO(C) Bokakhat / DDMA",
    polygon: [
      [26.7500, 93.4200],
      [26.7200, 93.7200],
      [26.5600, 93.7000],
      [26.5100, 93.5200],
      [26.6200, 93.4200],
    ],
  },
  {
    id: "CIR-02",
    circle: "Golaghat Revenue Circle",
    subdivision: "Golaghat Sadar",
    center: [26.5186, 93.9678],
    severity: "Critical",
    populationAffected: 48200,
    familiesAffected: 10400,
    villagesAffected: 54,
    deaths: 2,
    housesDamaged: 1380,
    cropAreaHa: 2100,
    reliefCamps: 12,
    campInmates: 4100,
    status: "Dhansiri 0.30m above danger level; Town Ward 4 & 9 waterlogged",
    source: "Circle Officer, Golaghat / DDMA",
    polygon: [
      [26.5800, 93.8800],
      [26.5900, 94.0800],
      [26.4400, 94.0600],
      [26.4200, 93.8800],
    ],
  },
  {
    id: "CIR-03",
    circle: "Khumtai Revenue Circle",
    subdivision: "Golaghat Sadar",
    center: [26.6340, 93.8850],
    severity: "High",
    populationAffected: 38400,
    familiesAffected: 8200,
    villagesAffected: 42,
    deaths: 2,
    housesDamaged: 1120,
    cropAreaHa: 1950,
    reliefCamps: 9,
    campInmates: 3200,
    status: "Doyang river surge; SH-1 Dhudar Ali submerged at Km 14",
    source: "Circle Officer, Khumtai / DDMA",
    polygon: [
      [26.6800, 93.7800],
      [26.7000, 93.9500],
      [26.5800, 93.9500],
      [26.5600, 93.7800],
    ],
  },
  {
    id: "CIR-04",
    circle: "Dergaon Revenue Circle",
    subdivision: "Golaghat Sadar",
    center: [26.7000, 93.9700],
    severity: "Moderate",
    populationAffected: 26500,
    familiesAffected: 5600,
    villagesAffected: 31,
    deaths: 1,
    housesDamaged: 740,
    cropAreaHa: 1450,
    reliefCamps: 6,
    campInmates: 2100,
    status: "Kakodonga embankment seepage controlled; agricultural fields inundated",
    source: "Circle Officer, Dergaon / DDMA",
    polygon: [
      [26.7400, 93.8500],
      [26.7400, 94.0600],
      [26.6500, 94.0500],
      [26.6500, 93.8800],
    ],
  },
  {
    id: "CIR-05",
    circle: "Morangi Revenue Circle",
    subdivision: "Golaghat Sadar",
    center: [26.4200, 93.8200],
    severity: "Moderate",
    populationAffected: 17500,
    familiesAffected: 3200,
    villagesAffected: 20,
    deaths: 1,
    housesDamaged: 480,
    cropAreaHa: 900,
    reliefCamps: 5,
    campInmates: 1500,
    status: "Numaligarh & Rangamati tea lowlands inundated; relief distribution active",
    source: "Circle Officer, Morangi / DDMA",
    polygon: [
      [26.5200, 93.7000],
      [26.5000, 93.8800],
      [26.3200, 93.8500],
      [26.3400, 93.6800],
    ],
  },
];

// CWC & WRD Hydrological Gauge Stations in Golaghat
export const GOLAGHAT_GAUGES_GEO = [
  {
    id: "GAUGE-GLT-01",
    river: "Dhansiri (South)",
    station: "Numaligarh Gauge Station",
    circle: "Bokakhat / Morangi",
    coords: [26.6200, 93.7500],
    level: 77.94,
    danger: 77.42,
    hfl: 79.98,
    status: "ABOVE DANGER LEVEL",
    trend: "STEADY",
    agency: "Central Water Commission (CWC)",
    lastObs: "22 Aug 2026, 12:00 IST",
  },
  {
    id: "GAUGE-GLT-02",
    river: "Dhansiri (South)",
    station: "Golaghat Town Bridge Gauge",
    circle: "Golaghat Sadar",
    coords: [26.5210, 93.9720],
    level: 91.80,
    danger: 91.50,
    hfl: 93.20,
    status: "ABOVE DANGER LEVEL",
    trend: "FALLING SLOWLY",
    agency: "Assam Water Resources Dept (WRD)",
    lastObs: "22 Aug 2026, 12:00 IST",
  },
  {
    id: "GAUGE-GLT-03",
    river: "Doyang",
    station: "Doyang Confluence Gauge",
    circle: "Khumtai",
    coords: [26.6420, 93.8780],
    level: 84.40,
    danger: 84.20,
    hfl: 86.10,
    status: "ABOVE DANGER LEVEL",
    trend: "RISING SLOWLY",
    agency: "Assam Water Resources Dept (WRD)",
    lastObs: "22 Aug 2026, 12:00 IST",
  },
  {
    id: "GAUGE-GLT-04",
    river: "Gelabil",
    station: "Bokakhat Road Bridge Gauge",
    circle: "Bokakhat",
    coords: [26.5920, 93.6120],
    level: 74.10,
    danger: 74.30,
    hfl: 75.80,
    status: "BELOW DANGER LEVEL",
    trend: "STEADY",
    agency: "District Hydrology Cell, Golaghat",
    lastObs: "22 Aug 2026, 12:00 IST",
  },
];

// Key Highway & Road Segments in Golaghat with Live Operational Status
export const GOLAGHAT_ROADS_GEO = [
  {
    id: "ROAD-01",
    name: "NH-715 (Kaziranga Wildlife Corridor)",
    category: "National Highway",
    status: "RESTRICTED",
    color: "#f59e0b",
    coords: [
      [26.5800, 93.4200],
      [26.5850, 93.6050],
      [26.6200, 93.7500],
      [26.7000, 93.9700],
    ],
    details: "Overtopped at Km 92. Regulated 30 km/h speed pilot escort active for animal migration.",
    connectivity: "Passable with Escort",
  },
  {
    id: "ROAD-02",
    name: "NH-129 / NH-29 (Numaligarh–Golaghat–Dimapur)",
    category: "National Highway",
    status: "OPEN",
    color: "#10b981",
    coords: [
      [26.6200, 93.7500],
      [26.5186, 93.9678],
      [26.4200, 93.8200],
      [26.2500, 93.8500],
    ],
    details: "Shoulder erosion repaired near Morangi. Open to two-way heavy traffic.",
    connectivity: "Fully Open",
  },
  {
    id: "ROAD-03",
    name: "SH-1 (Dhudar Ali: Golaghat–Khumtai–Kamargaon)",
    category: "State Highway",
    status: "PARTIALLY ACCESSIBLE",
    color: "#f97316",
    coords: [
      [26.5186, 93.9678],
      [26.6340, 93.8850],
      [26.6700, 93.8200],
    ],
    details: "0.20m standing water at Km 14 near Khumtai. Light motor vehicles and ambulances permitted.",
    connectivity: "Light Vehicles Only",
  },
  {
    id: "ROAD-04",
    name: "Bokakhat–Dhansirimukh PWD Road",
    category: "Major District Road",
    status: "CLOSED",
    color: "#ef4444",
    coords: [
      [26.5850, 93.6050],
      [26.6500, 93.6400],
      [26.6800, 93.6500],
    ],
    details: "Culvert approach washed away by backwaters. SDRF motorized boat ferry operational.",
    connectivity: "Impassable (Boat Transit)",
  },
];

// Active Relief Camps, Hospitals & Response Hubs in Golaghat
export const GOLAGHAT_FACILITIES_GEO = [
  {
    id: "CAMP-01",
    name: "Bokakhat Central Flood Shelter (Town Club)",
    circle: "Bokakhat",
    type: "RELIEF_CAMP",
    coords: [26.5860, 93.6020],
    inmates: 1420,
    capacity: 1600,
    doctorOnDuty: true,
    drinkingWater: "Mobile Tanker Plant",
    authority: "SDO(C) Bokakhat & DDMA",
    status: "OPERATIONAL",
  },
  {
    id: "CAMP-02",
    name: "Khumtai Higher Secondary School Camp",
    circle: "Khumtai",
    type: "RELIEF_CAMP",
    coords: [26.6320, 93.8820],
    inmates: 1150,
    capacity: 1300,
    doctorOnDuty: true,
    drinkingWater: "Halogen Tablets Supplied",
    authority: "Circle Officer Khumtai",
    status: "OPERATIONAL",
  },
  {
    id: "CAMP-03",
    name: "Morangi Model College Relief Camp",
    circle: "Morangi",
    type: "RELIEF_CAMP",
    coords: [26.4180, 93.8220],
    inmates: 980,
    capacity: 1200,
    doctorOnDuty: true,
    drinkingWater: "Borewell Chlorinated",
    authority: "Circle Officer Morangi",
    status: "OPERATIONAL",
  },
  {
    id: "CAMP-04",
    name: "Numaligarh High School Camp",
    circle: "Bokakhat / Morangi",
    type: "RELIEF_CAMP",
    coords: [26.6210, 93.7520],
    inmates: 850,
    capacity: 1000,
    doctorOnDuty: true,
    drinkingWater: "Packaged Pouches",
    authority: "DDMA Golaghat",
    status: "OPERATIONAL",
  },
  {
    id: "CAMP-05",
    name: "Dergaon Girls High School Camp",
    circle: "Dergaon",
    type: "RELIEF_CAMP",
    coords: [26.7020, 93.9680],
    inmates: 720,
    capacity: 900,
    doctorOnDuty: true,
    drinkingWater: "Chlorinated Tap",
    authority: "Circle Officer Dergaon",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-01",
    name: "Swahid Kushal Konwar Civil Hospital (SKKCH Golaghat)",
    circle: "Golaghat Sadar",
    type: "HOSPITAL",
    coords: [26.5150, 93.9740],
    bedsTotal: 250,
    bedsAvailable: 48,
    emergencyContact: "03774-280222",
    triageStatus: "District Referral Hub Active",
    contact: "03774-280222 (Control Room)",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-02",
    name: "Bokakhat Sub-Divisional Civil Hospital (SDCH)",
    circle: "Bokakhat",
    type: "HOSPITAL",
    coords: [26.5820, 93.6080],
    bedsTotal: 100,
    bedsAvailable: 22,
    emergencyContact: "03776-268244",
    triageStatus: "Emergency Triage Unit Deployed",
    contact: "03776-268244",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-03",
    name: "Numaligarh Refinery Hospital (NRL)",
    circle: "Morangi",
    type: "HOSPITAL",
    coords: [26.6120, 93.7650],
    bedsTotal: 50,
    bedsAvailable: 16,
    emergencyContact: "03776-265555",
    triageStatus: "Industrial Trauma & First Aid",
    contact: "03776-265555",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-04",
    name: "Sarupathar Community Health Centre (CHC)",
    circle: "Sarupathar",
    type: "HOSPITAL",
    coords: [26.1800, 93.8100],
    bedsTotal: 40,
    bedsAvailable: 12,
    emergencyContact: "03774-278233",
    triageStatus: "Sub-Divisional Primary Care",
    contact: "03774-278233",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-05",
    name: "Dergaon Model Hospital",
    circle: "Dergaon",
    type: "HOSPITAL",
    coords: [26.6980, 93.9720],
    bedsTotal: 30,
    bedsAvailable: 8,
    emergencyContact: "03776-244122",
    triageStatus: "First Referral Unit",
    contact: "03776-244122",
    status: "OPERATIONAL",
  },
];

// Verified Nearby Hospitals & Medical Facilities in and around Golaghat District
export const GOLAGHAT_HOSPITALS = [
  {
    id: "HOSP-01",
    name: "Swahid Kushal Konwar Civil Hospital (SKKCH Golaghat)",
    type: "Civil Hospital / District Referral Hospital",
    location: "Golaghat Town (Golaghat Sadar)",
    emergencyContact: "03774-280222",
    mainContact: "03774-280222",
    ambulanceAvailability: "4 On-site Ambulances (108 Link)",
    bedCapacity: 250,
    bedsAvailable: 48,
    medicalServices: "24/7 Emergency Triage, ICU, Trauma Care, Surgical Unit, Blood Bank, Pediatric Ward, Anti-Venom Bank",
    lastUpdated: "22 Aug 2026, 13:30 IST",
    source: "District Health Society, Golaghat",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-02",
    name: "Bokakhat Sub-Divisional Civil Hospital (SDCH)",
    type: "Sub-Divisional Civil Hospital",
    location: "Bokakhat Town (Bokakhat Circle)",
    emergencyContact: "03776-268244",
    mainContact: "03776-268244",
    ambulanceAvailability: "2 On-site Ambulances (108 Link)",
    bedCapacity: 100,
    bedsAvailable: 22,
    medicalServices: "Emergency Triage, Flood Inmate Ward, Maternity Unit, General Medicine, Snakebite Treatment, Chlorination Depot",
    lastUpdated: "22 Aug 2026, 13:30 IST",
    source: "District Health Society, Golaghat",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-03",
    name: "Sarupathar Community Health Centre (CHC)",
    type: "Community Health Centre",
    location: "Sarupathar (Dhansiri Sub-Division)",
    emergencyContact: "03774-278233",
    mainContact: "03774-278233",
    ambulanceAvailability: "1 Ambulance Available (108 Link)",
    bedCapacity: 40,
    bedsAvailable: 12,
    medicalServices: "Emergency First Aid, Inpatient Wards, Mother & Child Care, Waterborne Disease Screening",
    lastUpdated: "22 Aug 2026, 13:00 IST",
    source: "Sub-Divisional Health Cell, Dhansiri",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-04",
    name: "Dergaon Model Hospital / First Referral Unit (FRU)",
    type: "Model Hospital / FRU",
    location: "Dergaon Town (Dergaon Circle)",
    emergencyContact: "03776-244122",
    mainContact: "03776-244122",
    ambulanceAvailability: "1 Ambulance Available (108 Link)",
    bedCapacity: 30,
    bedsAvailable: 8,
    medicalServices: "General Medicine, Emergency Stabilization, Minor OT, Pediatric Care, Immunization",
    lastUpdated: "22 Aug 2026, 12:30 IST",
    source: "Block Medical Officer, Dergaon",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-05",
    name: "Khumtai Model Hospital / PHC",
    type: "Model Hospital / Primary Health Centre",
    location: "Khumtai (Khumtai Circle)",
    emergencyContact: "03774-295108",
    mainContact: "03774-295108",
    ambulanceAvailability: "108 Service on call",
    bedCapacity: 12,
    bedsAvailable: 4,
    medicalServices: "Outpatient Services, Emergency First Aid, Diarrhea & Infection Triage, Halogen Distribution",
    lastUpdated: "22 Aug 2026, 12:00 IST",
    source: "Block Medical Officer, Khumtai",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-06",
    name: "Numaligarh Refinery Limited (NRL) Hospital",
    type: "Industrial Multi-Specialty Hospital (Referral)",
    location: "Numaligarh (Morangi Circle)",
    emergencyContact: "03776-265555",
    mainContact: "03776-265555",
    ambulanceAvailability: "2 Critical Care Ambulances",
    bedCapacity: 50,
    bedsAvailable: 16,
    medicalServices: "24/7 Trauma Care, Burn Unit, ICU, Advanced Life Support, Emergency Referral Support for DDMA",
    lastUpdated: "22 Aug 2026, 13:00 IST",
    source: "NRL Medical Administration",
    status: "OPERATIONAL",
  },
  {
    id: "HOSP-07",
    name: "Morangi Block Primary Health Centre (BPHC)",
    type: "Block Primary Health Centre",
    location: "Kathalguri / Morangi (Morangi Circle)",
    emergencyContact: "108",
    mainContact: "Contact unavailable",
    ambulanceAvailability: "108 Ambulance Network",
    bedCapacity: 10,
    bedsAvailable: 2,
    medicalServices: "Primary Outpatient Care, Camp Medical Outreach, ORS & Anti-diarrheal Supply",
    lastUpdated: "22 Aug 2026, 11:30 IST",
    source: "District Health Society, Golaghat",
    status: "LIMITED SERVICES",
  },
  {
    id: "HOSP-08",
    name: "Kamargaon Primary Health Centre (PHC)",
    type: "Primary Health Centre",
    location: "Kamargaon (Khumtai / Bokakhat Border)",
    emergencyContact: "108",
    mainContact: "Contact unavailable",
    ambulanceAvailability: "108 Ambulance Network",
    bedCapacity: 6,
    bedsAvailable: 2,
    medicalServices: "Basic Emergency First Aid, Rapid Triage, Waterborne Disease Prophylaxis",
    lastUpdated: "22 Aug 2026, 11:00 IST",
    source: "District Health Society, Golaghat",
    status: "LIMITED SERVICES",
  },
];

// Verified Important Official Emergency Contacts for Golaghat Flood Response
export const GOLAGHAT_EMERGENCY_CONTACTS = [
  {
    id: "CONT-01",
    name: "District Emergency Operations Centre (DEOC) / Control Room",
    organization: "DDMA Golaghat / District Administration",
    purpose: "24/7 District Flood Disaster Helpline, Incident Reporting & Rescue Coordination",
    phone: "03774-280120",
    tollFree: "1077",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "DDMA Golaghat Official Registry",
  },
  {
    id: "CONT-02",
    name: "State Emergency Operations Centre (SEOC) Assam",
    organization: "Assam State Disaster Management Authority (ASDMA)",
    purpose: "Statewide Disaster Helpline & Inter-Agency Coordination",
    phone: "0361-2237221",
    tollFree: "1070",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "ASDMA Official Portal",
  },
  {
    id: "CONT-03",
    name: "District Administration / DC Office Golaghat",
    organization: "Office of the District Magistrate & DC Golaghat",
    purpose: "District Incident Command, Executive Requisitions & Relief Administration",
    phone: "03774-280221",
    tollFree: null,
    status: "OPERATIONAL",
    priority: "HIGH",
    source: "District Administration Golaghat",
  },
  {
    id: "CONT-04",
    name: "Bokakhat Sub-Divisional Control Room (SDO Civil)",
    organization: "Sub-Divisional Administration, Bokakhat",
    purpose: "Bokakhat Circle Relief Camps, Kaziranga NH-715 & Rescue Coordination",
    phone: "03776-268225",
    tollFree: null,
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "SDO(C) Bokakhat Office",
  },
  {
    id: "CONT-05",
    name: "Dhansiri Sub-Divisional Control Room (Sarupathar)",
    organization: "Sub-Divisional Administration, Dhansiri",
    purpose: "Dhansiri Sub-Division Flood Control, Relief Grants & Camp Coordination",
    phone: "03774-278220",
    tollFree: null,
    status: "24x7 OPERATIONAL",
    priority: "HIGH",
    source: "SDO(C) Dhansiri Office",
  },
  {
    id: "CONT-06",
    name: "District Police Control Room, Golaghat",
    organization: "Assam Police (Golaghat District)",
    purpose: "Law & Order, Traffic Escort, Highway Regulated Convoy (NH-715) & Emergency Search",
    phone: "03774-280333",
    tollFree: "112",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "Golaghat District Police",
  },
  {
    id: "CONT-07",
    name: "Emergency Medical & Ambulance Service (Mrityunjoy)",
    organization: "National Health Mission Assam / GVK EMRI",
    purpose: "24/7 Free Emergency Medical Ambulance & Patient Evacuation",
    phone: "108",
    tollFree: "108",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "NHM Assam Directory",
  },
  {
    id: "CONT-08",
    name: "Fire & Emergency Services, Golaghat",
    organization: "State Fire & Emergency Services Station, Golaghat",
    purpose: "Water Rescues, Inundation Pumping, Obstacle Clearance & Structural Evacuation",
    phone: "03774-280101",
    tollFree: "101",
    status: "24x7 OPERATIONAL",
    priority: "HIGH",
    source: "State Fire Service Assam",
  },
  {
    id: "CONT-09",
    name: "SDRF Golaghat Control Station",
    organization: "State Disaster Response Force (SDRF Assam)",
    purpose: "Deep-Water Motorized Boat Rescues, Evacuations & Breached Dyke Armoring Support",
    phone: "03774-280450",
    tollFree: "1077",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "SDRF Assam / DDMA Golaghat",
  },
  {
    id: "CONT-10",
    name: "NDRF 1st Battalion Emergency Control (Bokakhat Base)",
    organization: "National Disaster Response Force (NDRF)",
    purpose: "High-Water Search & Rescue, Flood Evacuation & Humanitarian Air/Boat Drops",
    phone: "0361-2840027",
    tollFree: "9435117246",
    status: "24x7 OPERATIONAL",
    priority: "CRITICAL",
    source: "1st Bn NDRF Control Room",
  },
  {
    id: "CONT-11",
    name: "Assam WRD Dhansiri Flood Control Room",
    organization: "Assam Water Resources Department (Dhansiri Division, Golaghat)",
    purpose: "Hydrological River Gauge Alerts, Embankment Patrol & Bilgaon Dyke Armoring",
    phone: "03774-280310",
    tollFree: null,
    status: "24x7 OPERATIONAL",
    priority: "HIGH",
    source: "WRD Dhansiri Division",
  },
  {
    id: "CONT-12",
    name: "APDCL Electricity Emergency & Breakdown Helpline",
    organization: "Assam Power Distribution Company Limited (Golaghat Electrical Division)",
    purpose: "Substation Status, Submerged Wire Hazard Reporting & Feeder Restoration",
    phone: "03774-280245",
    tollFree: "1912",
    status: "OPERATIONAL",
    priority: "MODERATE",
    source: "APDCL Golaghat",
  },
  {
    id: "CONT-13",
    name: "PHE Safe Drinking Water & Sanitation Helpline",
    organization: "Public Health Engineering Department (Golaghat Division)",
    purpose: "Mobile Drinking Water Tanker Requisition, Camp Chlorination & Disinfection",
    phone: "03774-280188",
    tollFree: null,
    status: "OPERATIONAL",
    priority: "MODERATE",
    source: "PHE Division Golaghat",
  },
];

// Embankment Breaches & Engineering Defense Hotspots in Golaghat
export const GOLAGHAT_DEFENSES_GEO = [
  {
    id: "DEF-01",
    name: "Bilgaon Dyke Breach (Dhansiri Right Bank)",
    river: "Dhansiri South",
    circle: "Golaghat Sadar",
    coords: [26.5450, 93.9200],
    type: "EMBANKMENT_BREACH",
    status: "ACTIVE_GEOBAG_ARMORING",
    details: "40m bank erosion. WRD Dhansiri Division and SDRF deployed with 12,000 geobags.",
  },
  {
    id: "DEF-02",
    name: "Numaligarh Dhansiri Bridge Abutment Protection",
    river: "Dhansiri South",
    circle: "Bokakhat",
    coords: [26.6210, 93.7480],
    type: "BRIDGE_PROTECTION",
    status: "STABILIZED",
    details: "Heavy boulder pitching completed on western approach slope. No structural shift.",
  },
  {
    id: "DEF-03",
    name: "Gelabil Flood Protection Bundh",
    river: "Gelabil",
    circle: "Bokakhat",
    coords: [26.6100, 93.6300],
    type: "DYKE_STABILIZATION",
    status: "CONTAINED",
    details: "Poly-geotextile sheet lining completed across 180m vulnerable section.",
  },
  {
    id: "DEF-04",
    name: "Kakodonga Left Bank Ring Bundh",
    river: "Kakodonga",
    circle: "Dergaon",
    coords: [26.6900, 93.9900],
    type: "EMBANKMENT_PROTECTION",
    status: "STABILIZED",
    details: "Seepage plugged with sandbags. Continuous 24h vigil by village defense party.",
  },
];

// Verified Inundation Extent Polygons (NRSC / ISRO Satellite Observation Derived)
export const GOLAGHAT_INUNDATION_ZONES = [
  {
    id: "INUND-01",
    name: "Dhansiri River Floodplain Inundation Corridor",
    source: "NRSC / ISRO Flood Inundation Product",
    satellite: "RISAT-1A (EOS-04) SAR & Sentinel-1",
    observation: "22 Aug 2026, 06:30 IST",
    status: "Preliminary satellite-derived observation",
    color: "#0284c7",
    fillOpacity: 0.45,
    polygon: [
      [26.5400, 93.9100],
      [26.5900, 93.8200],
      [26.6400, 93.7300],
      [26.6800, 93.6400],
      [26.6600, 93.6800],
      [26.6000, 93.7900],
      [26.5200, 93.9500],
    ],
  },
  {
    id: "INUND-02",
    name: "Bokakhat-Kaziranga Buffer Submergence Zone",
    source: "NRSC / ISRO Flood Inundation Product",
    satellite: "RISAT-1A SAR",
    observation: "22 Aug 2026, 06:30 IST",
    status: "Preliminary satellite-derived observation",
    color: "#dc2626",
    fillOpacity: 0.4,
    polygon: [
      [26.6000, 93.5200],
      [26.6800, 93.5000],
      [26.7200, 93.6500],
      [26.6400, 93.6800],
      [26.5700, 93.5800],
    ],
  },
  {
    id: "INUND-03",
    name: "Khumtai-Doyang Agricultural Lowland Inundation",
    source: "NRSC / ISRO Flood Inundation Product",
    satellite: "Sentinel-1 SAR",
    observation: "22 Aug 2026, 06:30 IST",
    status: "Preliminary satellite-derived observation",
    color: "#f59e0b",
    fillOpacity: 0.35,
    polygon: [
      [26.6200, 93.8600],
      [26.6600, 93.9000],
      [26.6100, 93.9400],
      [26.5700, 93.8900],
    ],
  },
];

// Initial Verified Alerts
export const INITIAL_ALERTS = [
  {
    id: "GLT-ALT-01",
    title: "Dhansiri River 0.52m Above Danger Level at Numaligarh",
    severity: "CRITICAL",
    location: "Numaligarh & Bokakhat (Golaghat)",
    timestamp: "22 Aug 2026, 13:00 IST",
    source: "Central Water Commission (CWC)",
    details: "Water level recorded at 77.94m (Danger Level: 77.42m). Downstream riverbank patrolling active along Bilgaon dyke.",
  },
  {
    id: "GLT-ALT-02",
    title: "NH-715 Kaziranga Wildlife Corridor Speed Advisory",
    severity: "HIGH",
    location: "Bokakhat to Kohora Sector (Km 92)",
    timestamp: "22 Aug 2026, 12:30 IST",
    source: "Assam Forest Dept & Golaghat District Police",
    details: "Regulated convoy pilot escort active. Speed limit strictly 30 km/h to protect migrating wildlife.",
  },
  {
    id: "GLT-ALT-03",
    title: "Dhansiri River Overflow in Golaghat Sadar Lowlands",
    severity: "HIGH",
    location: "Golaghat Town (Ward 4 & 9)",
    timestamp: "22 Aug 2026, 11:30 IST",
    source: "DDMA Golaghat Sadar Control Room",
    details: "River gauge recorded at 91.80m (+0.30m above danger level). Municipal drainage pumping units operational.",
  },
  {
    id: "GLT-ALT-04",
    title: "Drinking Water Chlorination & ORS Drive Across 48 Camps",
    severity: "MODERATE",
    location: "All Active Relief Shelters in Golaghat",
    timestamp: "22 Aug 2026, 09:30 IST",
    source: "District Health Society, Golaghat",
    details: "34 mobile medical units active. Over 85,000 chlorine tablets distributed to ensure potable drinking water.",
  },
];